on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push fesatech2
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASS }}
        server-dir: /
